In [120]:
import pandas as pd

In [121]:
df = pd.read_csv('dataset.csv')
df.head()

,team_a_rank,team_b_rank,team_a_form,team_b_form,is_home_a,h2h_wins_a,injured_a,injured_b,attack_a,defense_a,...,defense_b,goals_scored_last5_a,goals_conceded_last5_a,goals_scored_last5_b,goals_conceded_last5_b,weather_favorable_a,match_date,crowd_size,referee_experience,match_outcome
0,57,67,-0.671374,0.566596,0,5,0.0,0,56.473940,79.384784,...,79.839854,3,3,3,2,1,2023-01-01,28990,10,2
1,47,21,-0.713799,-0.160582,1,3,1.0,0,90.651993,82.502242,...,88.845831,7,11,4,4,1,2023-01-02,29821,14,2
2,59,45,1.425406,0.404748,0,1,0.0,2,87.976642,95.000000,...,95.000000,4,7,5,4,1,2023-01-03,32448,7,2
3,72,49,1.864414,0.351909,0,4,1.0,2,70.783685,64.206647,...,62.451135,12,5,3,2,0,2023-01-04,45829,11,2
4,46,50,-0.928882,-0.509021,1,1,1.0,2,57.166368,62.902922,...,71.612844,5,4,4,3,1,2023-01-05,46506,5,2

In [122]:
df.shape

(12000, 21)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   team_a_rank             12000 non-null  int64
 1   team_b_rank             12000 non-null  int64
 2   team_a_form             11657 non-null  float64
 3   team_b_form             12000 non-null  float64
 4   is_home_a               12000 non-null  int64
 5   h2h_wins_a              12000 non-null  int64
 6   injured_a               11629 non-null  float64
 7   injured_b               12000 non-null  int64
 8   attack_a                11632 non-null  float64
 9   defense_a               12000 non-null  float64
 10  attack_b                12000 non-null  float64
 11  defense_b               12000 non-null  float64
 12  goals_scored_last5_a    12000 non-null  int64
 13  goals_conceded_last5_a  12000 non-null  int64
 14  goals_scored_last5_b    12000 non-null  int64
 15  goals_conceded_last5_b  12000 non-null  int64
 16  weather_favorable_a     12000 non-null  int64
 17  match_date              12000 non-null  object
 18  crowd_size              12000 non-null  int64
 19  referee_experience      12000 non-null  int64
 20  match_outcome           12000 non-null  int64
dtypes: float64(7), int64(13), object(1)
memory usage: 1.9+ MB

In [124]:
df.describe()

,team_a_rank,team_b_rank,team_a_form,team_b_form,is_home_a,h2h_wins_a,injured_a,injured_b,attack_a,defense_a,attack_b,defense_b,goals_scored_last5_a,goals_conceded_last5_a,goals_scored_last5_b,goals_conceded_last5_b,weather_favorable_a,crowd_size,referee_experience,match_outcome
count,12000.000000,12000.000000,11657.000000,12000.000000,12000.000000,12000.00000,11629.000000,12000.000000,11632.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,49.415583,49.645167,-0.011245,0.003962,0.502750,2.97925,1.012383,1.007417,69.871248,69.926237,69.743484,69.989290,5.995583,4.996750,6.001667,5.038917,0.603083,29953.188750,9.448417,1.308250
std,15.010179,14.979162,1.001587,0.989446,0.500013,1.71111,1.003615,1.004795,14.134941,13.989253,14.049353,14.040455,2.448141,2.243805,2.454655,2.247144,0.489279,9961.780371,3.007146,0.885229
min,1.000000,1.000000,-3.000000,-3.000000,0.000000,0.00000,0.000000,0.000000,40.000000,40.000000,40.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5000.000000,1.000000,0.000000
25%,39.000000,39.000000,-0.700789,-0.667725,0.000000,2.00000,0.000000,0.000000,59.809084,59.956863,59.748031,60.140642,4.000000,3.000000,4.000000,3.000000,0.000000,23143.000000,7.000000,0.000000
50%,49.000000,50.000000,-0.007476,0.004420,1.000000,3.00000,1.000000,1.000000,69.862407,70.130212,69.909092,70.135723,6.000000,5.000000,6.000000,5.000000,1.000000,29890.000000,9.000000,2.000000
75%,59.000000,60.000000,0.675212,0.678833,1.000000,4.00000,2.000000,2.000000,80.284317,80.230051,79.905256,80.185426,8.000000,6.000000,8.000000,6.000000,1.000000,36662.000000,11.000000,2.000000
max,100.000000,100.000000,3.000000,3.000000,1.000000,10.00000,5.000000,5.000000,95.000000,95.000000,95.000000,95.000000,15.000000,15.000000,15.000000,15.000000,1.000000,68255.000000,21.000000,2.000000

In [125]:
df["match_outcome"].value_counts()

2    7121
0    3422
1    1457
Name: match_outcome, dtype: int64

In [126]:
df['team_a_form'] = df['team_a_form'].fillna(df['team_a_form'].median())
df['injured_a'] = df['injured_a'].fillna(df['injured_a'].median())
df['attack_a'] = df['attack_a'].fillna(df['attack_a'].median())
df.isnull().sum()

team_a_rank               0
team_b_rank               0
team_a_form               0
team_b_form               0
is_home_a                 0
h2h_wins_a                0
injured_a                 0
injured_b                 0
attack_a                  0
defense_a                 0
attack_b                  0
defense_b                 0
goals_scored_last5_a      0
goals_conceded_last5_a    0
goals_scored_last5_b      0
goals_conceded_last5_b    0
weather_favorable_a       0
match_date                0
crowd_size                0
referee_experience        0
match_outcome             0
dtype: int64

In [127]:
df['match_date'] = pd.to_datetime(df['match_date'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   team_a_rank             12000 non-null  int64
 1   team_b_rank             12000 non-null  int64
 2   team_a_form             12000 non-null  float64
 3   team_b_form             12000 non-null  float64
 4   is_home_a               12000 non-null  int64
 5   h2h_wins_a              12000 non-null  int64
 6   injured_a               12000 non-null  float64
 7   injured_b               12000 non-null  int64
 8   attack_a                12000 non-null  float64
 9   defense_a               12000 non-null  float64
 10  attack_b                12000 non-null  float64
 11  defense_b               12000 non-null  float64
 12  goals_scored_last5_a    12000 non-null  int64
 13  goals_conceded_last5_a  12000 non-null  int64
 14  goals_scored_last5_b    12000 non-null  int64
 15  goals_conceded_last5_b  12000 non-null  int64
 16  weather_favorable_a     12000 non-null  int64
 17  match_date              12000 non-null  datetime64[ns]
 18  crowd_size              12000 non-null  int64
 19  referee_experience      12000 non-null  int64
 20  match_outcome           12000 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(13)
memory usage: 1.9 MB

In [128]:
df['rank_diff'] = df['team_b_rank'] - df['team_a_rank']

df['attack_diff'] = df['attack_a'] - df['attack_b']

df['defense_diff'] = df['defense_a'] - df['defense_b']

df['goal_diff_last5'] = (
    df['goals_scored_last5_a']
    - df['goals_scored_last5_b']
)

df['injury_diff'] = df['injured_b'] - df['injured_a']
df['abs_rank_diff'] = abs(df['team_a_rank'] - df['team_b_rank'])
df['abs_attack_diff'] = abs(df['attack_a'] - df['attack_b'])
df['abs_defense_diff'] = abs(df['defense_a'] - df['defense_b'])
df['abs_form_diff'] = abs(df['team_a_form'] - df['team_b_form'])

df['abs_goal_diff'] = abs(
    df['goals_scored_last5_a'] -
    df['goals_scored_last5_b']
)
df['similar_strength'] = (
    (df['abs_rank_diff'] <= 5) &
    (df['abs_attack_diff'] <= 5) &
    (df['abs_defense_diff'] <= 5)
).astype(int)

In [129]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

In [130]:
X = df.drop(["match_outcome", "match_date"], axis=1)
y = df["match_outcome"]

In [131]:
num_cols = X.select_dtypes(include=["int64","float64"]).columns

In [132]:
preprocessor = ColumnTransformer([
        ("num", StandardScaler(), num_cols)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['team_a_rank', 'team_b_rank', 'team_a_form', 'team_b_form', 'is_home_a',
       'h2h_wins_a', 'injured_a', 'injured_b', 'attack_a', 'defense_a',
       'attack_b', 'defense_b', 'goals_scored_last5_a',
       'goals_conceded_last5_a', 'goals_scored_last5_b',
       'goals_conceded_last5_b', 'weather_favorable_a', 'crowd_size',
       'referee_experience', 'rank_diff', 'attack_diff', 'defense_diff',
       'goal_diff_last5', 'injury_diff', 'abs_rank_diff', 'abs_attack_diff',
       'abs_defense_diff', 'abs_form_diff', 'abs_goal_diff'],
      dtype='object'))])

In [133]:
lr_model = Pipeline([
    ("prep", preprocessor),
    ("clf", LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42))
])
rf_model = Pipeline([
    ('smote', SMOTE(random_state=42)),
    ("prep", preprocessor),
    ("clf", RandomForestClassifier(n_estimators=300,class_weight='balanced',random_state=42))
])

In [134]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def evaluate_model(model, name):
    print(f"\n{'='*20} {name} {'='*20}")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)
    
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nROC-AUC (OVR):", roc_auc_score(y_test, y_proba, multi_class='ovr'))

In [135]:
evaluate_model(lr_model, "Logistic Regression")
evaluate_model(rf_model, "Random Forest")

==================== Logistic Regression ====================
Accuracy: 0.6970833333333334

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.74      0.77       685
           1       0.23      0.51      0.31       291
           2       0.91      0.71      0.80      1424

    accuracy                           0.70      2400
   macro avg       0.64      0.65      0.63      2400
weighted avg       0.80      0.70      0.73      2400


Confusion Matrix:
[[ 508  154   23]
 [  70  147   74]
 [  63  343 1018]]

ROC-AUC (OVR): 0.8480103808650954

==================== Random Forest ====================
Accuracy: 0.7383333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.76      0.75       685
           1       0.20      0.15      0.17       291
           2       0.82      0.85      0.83      1424

    accuracy                           0.74      2400
   macro avg       0.59      0.59      0.58      2400
weighted avg       0.72      0.74      0.73      2400


Confusion Matrix:
[[ 523   58  104]
 [  89   44  158]
 [  97  122 1205]]

ROC-AUC (OVR): 0.8202776667501407

In [136]:
from xgboost import XGBClassifier

xgb = Pipeline([
    ("prep", preprocessor),
    ("clf", XGBClassifier(
        n_estimators=600,
        max_depth=6,
        learning_rate=0.04,
        subsample=0.85,
        colsample_bytree=0.8,
        objective='multi:softprob',
        num_class=3,
        random_state=42,
        eval_metric='mlogloss',
        verbosity=0,
        scale_pos_weight=2.0   # Helps with minority classes
    ))
])

In [137]:
evaluate_model(xgb, "XGBoost")

==================== XGBoost ====================
Accuracy: 0.7804166666666666

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.80      0.77       685
           1       0.35      0.02      0.04       291
           2       0.80      0.93      0.86      1424

    accuracy                           0.78      2400
   macro avg       0.63      0.58      0.56      2400
weighted avg       0.73      0.78      0.73      2400


Confusion Matrix:
[[ 549    6  130]
 [  95    6  190]
 [ 101    5 1318]]

ROC-AUC (OVR): 0.8306609852158565